runtime: python38 # or another supported version

instance_class: F2

env_variables:
  BUCKET_NAME: "example-gcs-bucket"


handlers:
- url: /viewer/
  static_dir: viewer

- url: /iLearnML/
  static_dir: templates
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto